name: BCP Pipeline

permissions:
  contents: write

on:
  schedule:
    - cron: '0 9 * * 1'   # lunes
    - cron: '0 9 * * 3'   # miércoles
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python pipeline.py

      - name: Commit and push CSV files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add *.csv
          git commit -m "update data $(date +'%Y-%m-%d')" || echo "no changes"
          git push
